<?php

/**
 * KeywordWhoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KeywordWhoTable extends Doctrine_Table
{
  public function uniqueSave($keyword)
  {
    $obj = $this->findOneByWho($keyword);
    if (!$obj)
    {
      $obj = new KeywordWho();
      $obj->setWho($keyword);
      $obj->save();
    }

    return $obj;
  }
  /**
   * Returns an instance of this class.
   *
   * @return object KeywordWhoTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('KeywordWho');
  }
}
