<?php

/**
 * KeywordDoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KeywordDoTable extends Doctrine_Table
{
  public function uniqueSave($keyword)
  {
    $obj = $this->findOneByDo($keyword);
    if (!$obj)
    {
      $obj = new KeywordDo();
      $obj->setDo($keyword);
      $obj->save();
    }

    return $obj;
  }

  public function getRand()
  {
    $results = $this->createQuery()
      ->select('id')
      ->addSelect('do')
      ->orderBy('RAND()')
      ->limit(1)
      ->fetchOne(array(), Doctrine::HYDRATE_NONE);

    if (!$results)
    {
      return false;
    }

    return array('id' => $results[0], 'do' => $results[1]);
  }

  /**
   * Returns an instance of this class.
   *
   * @return object KeywordDoTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('KeywordDo');
  }
}
