<?php

/**
 * KeywordWhereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KeywordWhereTable extends Doctrine_Table
{
  public function uniqueSave($keyword)
  {
    $obj = $this->findOneByWhere($keyword);
    if (!$obj)
    {
      $obj = new KeywordWhere();
      $obj->setWhereis($keyword);
      $obj->save();
    }

    return $obj;
  }

  public function getRand()
  {
    $results = $this->createQuery()
      ->select('id')
      ->addSelect('whereis')
      ->orderBy('RAND()')
      ->limit(1)
      ->fetchOne(array(), Doctrine::HYDRATE_NONE);

    if (!$results)
    {
      return false;
    }

    return array('id' => $results[0], 'where' => $results[1]);
  }
  /**
   * Returns an instance of this class.
   *
   * @return object KeywordWhereTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('KeywordWhere');
  }
}
