<?php

/**
 * KeywordWhereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KeywordWhereTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KeywordWhereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KeywordWhere');
    }
}