<?php

/**
 * KeywordDoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KeywordDoTable extends Doctrine_Table
{
  public function uniqueSave($keyword)
  {
    $obj = $this->findOneByDo($keyword);
    if (!$obj)
    {
      $obj = new KeywordDo();
      $obj->setDo($keyword);
      $obj->save();
    }

    return $obj;
  }

  /**
   * Returns an instance of this class.
   *
   * @return object KeywordDoTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('KeywordDo');
  }
}
