<?php

/**
 * KeywordWhoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KeywordWhoTable extends Doctrine_Table
{
  protected static $count = null;

  public function uniqueSave($keyword)
  {
    $obj = $this->findOneByWho($keyword);
    if (!$obj)
    {
      $obj = new KeywordWho();
      $obj->setWho($keyword);
      $obj->save();
    }

    return $obj;
  }

  public function getRand()
  {
    if (null == self::$count)
    {
      self::$count = $this->createQuery()
        ->select('COUNT(*)')
        ->fetchOne(array(), Doctrine::HYDRATE_NONE);
    }

    $id = urabotToolkit::getRand(self::$count[0]);
    $results = $this->createQuery()
      ->select('id')
      ->addSelect('who')
      ->where('id = ?', $id)
      ->limit(1)
      ->fetchOne(array(), Doctrine::HYDRATE_NONE);

    if (!$results)
    {
      return false;
    }

    return array('id' => $results[0], 'who' => $results[1]);
  }

  /**
   * Returns an instance of this class.
   *
   * @return object KeywordWhoTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('KeywordWho');
  }
}
