<?php

/**
 * LastIdTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LastIdTable extends Doctrine_Table
{
  public function uniqueSave($type, $twitter_id)
  {
    $obj = $this->findOneByType($type);
    if (!$obj)
    {
      $obj = new LastId();
      $obj->setType($type);
    }
    $obj->setTwitterId($twitter_id);

    return $obj->save();
  }

  public function getLastTwitterId($type)
  {
    $result = $this->createQuery()
      ->select('twitter_id')
      ->where('type = ?', $type)
      ->orderBy('twitter_id DESC')
      ->limit(1)
      ->fetchOne(array(), Doctrine::HYDRATE_NONE);

    if (!$result)
    {
      return '1';
    }

    return $result[0];
  }

  /**
   * Returns an instance of this class.
   *
   * @return object LastIdTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('LastId');
  }
}
