<?php

/**
 * LastId
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    urabot
 * @subpackage model
 * @author     Shinichi Urabe
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LastId extends BaseLastId
{
  const TYPE_RAND_WORDS = 1;
}
