options:
  charset: utf8
actAs: [Timestampable]

LastId:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "プライマリーキー" }
    twitter_id: { type: integer(10), notnull: true, comment: "Twitter Id" }
    type: { type: integer(2), default: 1, notnull: true, comment: "タイプ" }
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
    comment: "誰が"

KeywordWho:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "プライマリーキー" }
    who: { type: string(64), default: "", notnull: true, comment: "誰が" }
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8

KeywordWhere:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "プライマリーキー" }
    whereis: { type: string(64), default: "", notnull: true, comment: "どこで" }
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8

KeywordDo:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "プライマリーキー" }
    do: { type: string(64), default: "", notnull: true, comment: "何をした" }
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8

CreatedHistory:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "プライマリーキー" }
    keyword_who_id: { type: integer(4), notnull: true, comment: "誰が" }
    keyword_where_id: { type: integer(4), notnull: true, comment: "どこで" }
    keyword_do_id: { type: integer(4), notnull: true, comment: "何をした" }
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
  relations:
    KeywordWho:
      onDelete: cascade
    KeywordWhere:
      onDelete: cascade
    KeywordDo:
      onDelete: cascade
  indexes:
    keyword_who_id_keyword_where_id_keyword_do_id:
      fields: [keyword_who_id, keyword_where_id, keyword_do_id]
      type: unique
