options:
  charset: utf8
actAs: [Timestampable]

KeywordWho:
  actAs: [Timestampable]
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "プライマリーキー" }
    who: { type: string(64), default: "", notnull: true, comment: "誰が" }
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
    comment: "誰が"

KeywordWhere:
  actAs: [Timestampable]
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "プライマリーキー" }
    where: { type: string(64), default: "", notnull: true, comment: "どこで" }
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
    comment: "どこで"

KeywordDo:
  actAs: [Timestampable]
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "プライマリーキー" }
    do: { type: string(64), default: "", notnull: true, comment: "何をした" }
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
    comment: "何をした"

CreatedHistory:
  actAs: [Timestampable]
  columns:
    id: { type: integer(4), primary: true, autoincrement: true, comment: "プライマリーキー" }
    keyword_who_id: { type: integer(4), notnull: true, comment: "誰が" }
    keyword_where_id: { type: integer(4), notnull: true, comment: "どこで" }
    keyword_do_id: { type: integer(4), notnull: true, comment: "何をした" }
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
    comment: "何がどこで何をした"
  relations:
    KeywordWho:
      onDelete: cascade
    KeywordWhere:
      onDelete: cascade
    KeywordDo:
      onDelete: cascade
  indexes:
    keyword_who_id_keyword_where_id_keyword_do_id:
      fields: [keyword_who_id, keyword_where_id, keyword_do_id]
      type: unique
